In [1]:
# 실습1 -> 5번째 셀
# 실습2 -> 7번째 셀

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
#Creating a Numpy Array

list = [1,2,3,4]

arr = np.array(list)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
# dtype attribute
print(arr.dtype)

a = np.array([1,1.4,"1.1, 1.2, 2.5"])
print(a.dtype)

int64
<U32


In [10]:
"""
Operation
"""

prices = [30,24,40,20,20,45,50,35]
price_arr = np.array(prices)

new_prices = [price - 5 for price in prices]
print(new_prices)

price_arr -= 5
print(price_arr)

[25, 19, 35, 15, 15, 40, 45, 30]
[25 19 35 15 15 40 45 30]


In [31]:
#실습 1

test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])
print("-------test1 test2 test3-------")
print(test_1)
print(test_2)
print(test_3)

print("-------test3 fixed-------")
test_3_fixed = test_3
test_3_fixed += 2
print(test_3_fixed)

print("-------total grade-------")
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

print("-------final grade-------")
final_grade = total_grade /3
print(final_grade)

print("-------student_scores-------")
student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print("-------jeremy_test_2-------")
jeremy_test_2 = student_scores[1,3]
print(jeremy_test_2)

print("-------cody_total-------")
cody_total = student_scores[:,4]
print(cody_total)

-------test1 test2 test3-------
[92 94 88 91 87]
[ 79 100  86  93  91]
[87 85 72 90 92]
-------test3 fixed-------
[89 87 74 92 94]
-------total grade-------
[260 281 248 276 272]
-------final grade-------
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
-------student_scores-------
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
-------jeremy_test_2-------
93
-------cody_total-------
[87 91 94]


In [36]:
"""
Logical Operations with Arrays
"""

a = np.array([10,2,2,3,4,5,3,9,8,7])
mask = a > 5
print(mask)

selected = a[a>5]
print(selected)

selected = a[(a>5) | (a<4)]
print(selected)

[ True False False False False False False  True  True  True]
[10  9  8  7]
[10  2  2  3  3  9  8  7]


In [43]:
# 실습2

porridge = np.array([79,65,50,63,56,90,85,98,79,51])

print("---cold---")
cold = porridge[porridge < 60]
print(cold)
print()

print("---hot---")
hot = porridge[porridge > 80]
print(hot)
print()

print("---just_right---")
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)
print()




---cold---
[50 56 51]

---hot---
[90 85 98]

---just_right---
[79 65 63 79]

